"""Golden-master tests: parse_export + format_markdown reproduce chat.md.

The committed examples/sample_export/chat.md was generated by this very
pipeline (--no-cache, no media). These tests lock it in as a golden oracle —
byte-exact reproduction catches composite regressions that per-function
tests cannot see — and assert determinism: same logical input produces
identical bytes regardless of message-list or transcript-dict iteration
order.

The sample export contains zero media files that resolve on disk (every
reference is a "(File not included...)" / "(File unavailable...)"
placeholder, which the parser resolves to None), so transcripts={} is the
exact input the real pipeline would produce.
"""

import difflib
import random
from pathlib import Path

from tg_chat_to_md.formatter import format_markdown
from tg_chat_to_md.models import Message
from tg_chat_to_md.parser import parse_export

REPO = Path(__file__).resolve().parents[1]
SAMPLE_DIR = REPO / "examples" / "sample_export"
GOLDEN = SAMPLE_DIR / "chat.md"


def _load_sample() -> tuple[str, list[Message]]:
    """Parse the committed sample export, guarding its no-media premise.

    The golden pipeline ran with transcripts={} because the demo references
    no files that resolve on disk; assert that premise so a future fixture
    edit cannot silently invalidate the golden comparison.
    """
    chat_name, _chat_id, messages = parse_export(SAMPLE_DIR)
    assert not any(m.file for m in messages)
    return chat_name, messages


def _golden_diff(actual: str) -> str:
    """Unified diff (committed golden vs actual output) for failure reports."""
    return "\n".join(
        difflib.unified_diff(
            GOLDEN.read_text(encoding="utf-8").splitlines(),
            actual.splitlines(),
            fromfile="examples/sample_export/chat.md",
            tofile="format_markdown()",
            lineterm="",
        )
    )


def _render(
    chat_name: str, messages: list[Message], transcripts: dict[str, str] | None = None
) -> str:
    """Render the sample exactly like the CLI does (Phase 4 of tg_chat_to_md)."""
    msg_index = {m.id: m for m in messages}
    return format_markdown(messages, chat_name, transcripts or {}, msg_index)


# ---------------------------------------------------------------------------
# Golden oracle: byte-exact reproduction of the committed chat.md
# ---------------------------------------------------------------------------
def test_golden_parse_and_format_reproduce_chat_md() -> None:
    chat_name, messages = _load_sample()
    golden = GOLDEN.read_text(encoding="utf-8")

    actual = _render(chat_name, messages)

    # Byte-exactness: a unified diff is the review artifact on any drift.
    assert actual == golden, f"Golden drift:\n{_golden_diff(actual)}"


def test_golden_document_contains_expected_markers() -> None:
    """Sanity markers (the byte-exact comparison above is the real oracle)."""
    chat_name, messages = _load_sample()
    md = _render(chat_name, messages)

    # Exactly the three days present in the fixture, in chronological order.
    headers = [line for line in md.splitlines() if line.startswith("## ")]
    assert headers == [
        "## 4 сентября 2026",
        "## 5 сентября 2026",
        "## 6 сентября 2026",
    ]

    markers = [
        "**без опозданий**",  # bold text entity
        "`@park\\_news`",  # mention entity with escaped underscore
        "> ↩ В ответ на **Аня** (09:01):",  # reply block
        "> ↪ Переслано от **Лес и парк** (канал)",  # forwarded block
        "👍 ×5 (Борис, Вера, Дима и ещё 2)",  # reactions with name overflow
        "*(отредактировано 09:11)*",  # edited marker
        "\\*звёздочки\\* и \\[квадратные скобки\\]",  # markdown escaping
    ]
    for marker in markers:
        assert marker in md


# ---------------------------------------------------------------------------
# Determinism: same logical input -> identical bytes, any iteration order
# ---------------------------------------------------------------------------
def test_golden_independent_of_message_iteration_order() -> None:
    """A permutation of the message list must not change the output bytes."""
    chat_name, messages = _load_sample()
    golden = GOLDEN.read_text(encoding="utf-8")

    shuffled = list(messages)
    random.Random(0).shuffle(shuffled)
    assert shuffled != messages  # guard: the permutation actually permutes

    actual = _render(chat_name, shuffled)

    assert actual == golden, f"Shuffled input drift:\n{_golden_diff(actual)}"


def test_golden_independent_of_transcripts_insertion_order() -> None:
    """Transcript-dict key order must not change the output bytes."""
    chat_name, messages = _load_sample()
    golden = GOLDEN.read_text(encoding="utf-8")

    # The sample resolves no media files, but the formatter must stay
    # insensitive to transcript-dict iteration order even with entries.
    ordered = {f"/media/msg{i}.ogg": f"расшифровка {i}" for i in range(40)}
    reversed_order = dict(reversed(list(ordered.items())))
    assert list(reversed_order) == list(reversed(ordered))

    for transcripts in ({}, ordered, reversed_order):
        actual = _render(chat_name, messages, transcripts)
        assert actual == golden, f"Transcript drift:\n{_golden_diff(actual)}"
